version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 4000:5432
    environment:
      POSTGRES_PASSWORD: cperv_db_solar
      POSTGRES_DB: cperv
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  